[2024-03-23T19:43:04.924+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_to_bigquery.extract_csv_file manual__2024-03-23T19:43:03.060824+00:00 [queued]>
[2024-03-23T19:43:04.938+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_to_bigquery.extract_csv_file manual__2024-03-23T19:43:03.060824+00:00 [queued]>
[2024-03-23T19:43:04.940+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-03-23T19:43:04.962+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): extract_csv_file> on 2024-03-23 19:43:03.060824+00:00
[2024-03-23T19:43:04.971+0000] {standard_task_runner.py:60} INFO - Started process 9001 to run task
[2024-03-23T19:43:04.976+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_to_bigquery', 'extract_csv_file', 'manual__2024-03-23T19:43:03.060824+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpnvf2eriu']
[2024-03-23T19:43:04.980+0000] {standard_task_runner.py:88} INFO - Job 29: Subtask extract_csv_file
[2024-03-23T19:43:05.050+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_to_bigquery.extract_csv_file manual__2024-03-23T19:43:03.060824+00:00 [running]> on host 8a685a05c3f5
[2024-03-23T19:43:05.151+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='minhduc' AIRFLOW_CTX_DAG_ID='etl_to_bigquery' AIRFLOW_CTX_TASK_ID='extract_csv_file' AIRFLOW_CTX_EXECUTION_DATE='2024-03-23T19:43:03.060824+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-23T19:43:03.060824+00:00'
[2024-03-23T19:43:05.157+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Jobs/pipline_jobs.py", line 8, in load_dataset
    df = pd.read_csv(file_path,encoding='unicode_escape')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/Online_Retail.csv'
[2024-03-23T19:43:05.171+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_to_bigquery, task_id=extract_csv_file, execution_date=20240323T194303, start_date=20240323T194304, end_date=20240323T194305
[2024-03-23T19:43:05.187+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 29 for task extract_csv_file ([Errno 2] No such file or directory: '/opt/airflow/data/Online_Retail.csv'; 9001)
[2024-03-23T19:43:05.230+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-23T19:43:05.262+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
